import "~/styles/globals.css";
import { Quicksand } from 'next/font/google';
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { InitDataProvider } from '~/telegram/InitDataContext';
import TelegramInit from '~/telegram/TelegramInit';

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-quicksand',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <InitDataProvider>
      <html lang="en" className={quicksand.className}>
        <body>
          <TRPCReactProvider>
            {children}
          </TRPCReactProvider>
          <TelegramInit />
        </body>
      </html>
    </InitDataProvider>
  );
}
