import "~/styles/globals.css";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { InitDataProvider } from '~/telegram/InitDataContext';
import TelegramInit from '~/telegram/TelegramInit';
import { Gowun_Dodum } from 'next/font/google'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const gowunDodum = Gowun_Dodum({
  subsets: ['latin'],
  weight: ['400'], // Specify weights you need, '400' is regular
  variable: '--font-gowun-dodum',
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <InitDataProvider>
      <html lang="en" className={gowunDodum.className}>
        <body>
          <TRPCReactProvider>
            {children}
          </TRPCReactProvider>
          <TelegramInit />
        </body>
      </html>
    </InitDataProvider>
  );
}
